AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scanAChainTransferBChainToken

  Sample SAM Template for scanAChainTransferBChainToken

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  scanAChainTransferBChainTokenFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        scanAChainTransferBChainToken:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  scanAChainTransferBChainTokenApi:
    Description: "API Gateway endpoint URL for Prod stage for scanAChainTransferBChainToken function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
  scanAChainTransferBChainTokenFunction:
    Description: "scanAChainTransferBChainToken Lambda Function ARN"
    Value: !GetAtt scanAChainTransferBChainTokenFunction.Arn
  scanAChainTransferBChainTokenFunctionIamRole:
    Description: "Implicit IAM Role created for scanAChainTransferBChainToken function"
    Value: !GetAtt scanAChainTransferBChainTokenFunctionRole.Arn
